---
- name: grabbing prefix list
  shell: cat "{{ file }}"
  register: result
  changed_when: False
- name: variable work
  set_fact:
    pl_source: "{{ result.stdout_lines }}"
- name: remove prior build temp files
  file: path="{{ build_dir }}/pl-PL-{{ item }}.conf" state=absent
  with_items: "{{ types }}"
