---

- name: Pull info for config diff
  napalm_install_config:
    provider: "{{ cli }}"
    dev_os: ios
    config_file: /etc/ansible/build/pl-PL-ios.conf
    commit_changes: False
    get_diffs: True
    diff_file: ./diff/ios/{{ inventory_hostname }}_diff
    optional_args: {'inline_transfer': True , 'secret': '<password>'}

- name: Grab diff
  shell: cat ./diff/ios/{{ inventory_hostname }}_diff
  register: commit_changes
  changed_when: False

- name: Proposed changes listed below, empty brackets [] denotes no changes.
  debug: msg="{{ commit_changes.stdout_lines }}"

- pause: prompt='Review proposed changes. Press return to continue. Press Ctrl+c and then "a" to abort'

- name: Implement changes for IOS brdr's
  napalm_install_config:
    provider: "{{ cli }}"
    dev_os: ios
    config_file: /etc/ansible/build/pl-PL-ios.conf
    commit_changes: True
    get_diffs: False
    optional_args: {'inline_transfer': True , 'secret': '<password>'}
  notify:
    - get_bgp
    - Soft_clear_ebgp
