---
- name: "get dir"
  hosts: 
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "script_password"
      prompt: "Enter password for user script"
      private: yes

  vars:

    - cli:
        host: "{{ inventory_hostname }}"
        username: script
        password: "{{ script_password }}"

  tasks:

    - name: "Clear out ./tmp folder"
      file:
        path: ./tmp
        state: absent
      run_once: true
      delegate_to: localhost
      changed_when: no
      check_mode: no

    - name: "re-create tmp folder"
      file:
        path: ./tmp
        state: directory
      run_once: true
      delegate_to: localhost
      changed_when: no
      check_mode: no

    - napalm_get_facts:
        provider: "{{ cli }}"
        dev_os: iosxr
        filter: 'facts'
      register: facts

    - iosxr_command:
        commands:
          - 'dir harddisk: | include total'
        provider: "{{ cli }}"
      register: dir

    - name: "save data to files with template"
      template:
        src: "./templates/code-prep.j2"
        dest: "./tmp/{{ inventory_hostname }}.txt"
      changed_when: no
      check_mode: no
